news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('training/', views.training, name='training'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('', include('web.urls')),
]

news/models.py
from django.db import models
from django.utils import timezone


class ArtikelPost(models.Model):
    überschrift = models.TextField(max_length=50)
    inhalt = models.TextField(max_length=10000)
    created_at = models.DateTimeField(max_length=10, default=timezone.now)

web/models.py
from django.db import models

# Create your models here.

web/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20, label='Benutzername:')
    password = forms.CharField(max_length=35, label='Password:', widget=forms.PasswordInput)





class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, label='Benutzername:')
    password = forms.CharField(max_length=35, label='Password:', widget=forms.PasswordInput)

news/views.py

from django.shortcuts import render


def index(request):
    return render(request, 'news/base.html')






web/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import RegisterForm, LoginForm


def index(request):
    return render(request, 'web/base.html')

def training(request):
    return render(request, 'web/training.html')

def register_view(request):
    register_form = RegisterForm()
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password']
            User.objects.create_user(username=username, password=password)
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
    return render(request, 'web/register.html', {'register_form': register_form})


def login_view(request):
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
        else:

            if user:
                login(request, user)
    return render(request, 'web/login.html', {'login_form': login_form})


def logout_view(request):
    logout(request)
    return redirect(reverse('web:index'))


news/templates/news/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FSV - News</title>

    <link rel="stylesheet" href="{% static 'Style/style.css' %}">
</head>
<body>
    <h1>News</h1>
</body>
</html>

web/templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%} Frankenberger Schwimmverein{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'Style/style.css' %}">
	{% block style %} <link rel="stylesheet" href="{% static 'Style/home.css' %}"> {% endblock %}
</head>

    <body>
			<div id="container">
				<header>
				</header>
				<nav>
					<ul>
						<li><a href="{% url 'web:index' %}">Home</a></li>
						<li><a href="{% url 'web:training' %}">Training</a></li>
						<li><a href="kontakt.html">Kontakt</a></li>
						<li><a href="{% url 'news:index' %}">Artikel</a></li>
						<li><a href="termine.html">Termine</a></li>
					</ul>
				</nav>

				{% block mainForm %}

				 <div id="main">
					<div id="top">
					</div>
					<div class="fling-minislide">
						<img src="{% static 'Style/orang.png' %}" alt="Slide 4" />
						<img src="{% static 'Style/grün.png' %}"  alt="Slide 3" />
						<img src="{% static 'Style/pink.png' %}" alt="Slide 2" />
						<img src="{% static 'Style/blau.png' %}"  alt="Slide 1" />
					</div>

					<div id="content">
						<h1>News</h1>


					</div>
				</div>


					<div id="rechts">
						<div id="wettkämpfe">
							<h3>Wettkämpfe</h3>
							<p id="p1">26.01.2019</p>
							<p id="p2">1. Wintermeeting - Eibel</p>
							<p id="p1">10.02.2019</p>
							<p id="p2">DMS - Frankenberg</p>
						</div>

						<div id="aktuelles1">
							<div id="bild">
								<img src="{% static 'Style/logo.png' %}"  height="30px">
							</div>
							<a href="maischwimmen.html">Maischwimmen</a>
						</div>
						<div id="aktuelles2">
							<div id="bild">
								<img src="{% static 'Style/logo.png' %}" height="30px">
							</div>
							<a href="trainingslager.html">Trainingslager</a>
						</div>
					</div>
				</div>

				{% endblock %}

			</div>
			<footer id="footer">
                <p><a href="impressum.html">Impressum</a></p>
				{% if request.user.is_authenticated %}
				<p><a href="{% url 'web:logout' %}">Logout</a></p>
				{% else %}
				<p><a href="{% url 'web:login' %}">Login</a></p>
				<p><a href="{% url 'web:register' %}">Registrieren</a></p>
				{% endif %}
            </footer>
		</body>
</html>

web/templates/web/login.html
{% extends 'web/base.html' %}
{% load static %}

{% block title%} FSV - Login {% endblock %}
{% block style%} <link rel="stylesheet" href="{% static 'Style/login.css' %}"> {% endblock %}


{% block mainForm %}

    <h1>Login</h1>
    <p>Dieser Bereich ist nur für Befugte</p>

    <form method="post" action="">
        {% csrf_token %}
        {{ login_form.as_p }}
        <button id="button" type="submit">Login</button>
    </form>

{% endblock %}

web/templates/web/register.html
{% extends 'web/base.html' %}

{% block titel %}FSV - Registrieren{% endblock %}

{% block mainForm %}

    <h1>Registrieren</h1>
    <p>Dieser Bereich ist nur für Befugte</p>

    <form method="post" action="">
        {% csrf_token %}
        {{ register_form.as_p }}
        <button id="button" type="submit">Erstellen</button>
    </form>

{% endblock %}

web/templates/web/training.html
{% extends 'web/base.html' %}
{% load static %}

{% block title%} FSV - Training {% endblock %}
{% block style%} <link rel="stylesheet" href="{% static 'Style/trainingszeiten.css' %}"> {% endblock %}


{% block mainForm %}

    <div id="main">
    	<h1>Trainingszeiten</h1>
		<p><h3>Stand 20.01.2018</h3></p>
		<p><h3>In der Hallenbadsaison 2017/2018 sind die Trainingszeiten wie folgt:</h3></p>
		<table>
			<tr>
				<th>Uhrzeit</th>
				<th>Montag</th>
				<th>Dienstag</th>
				<th>Mittwoch</th>
				<th>Donnerstag</th>
				<th>Freitag</th>
			</tr>
			<tr>
				<td id="time">13:00-14:45</td>
				<td>---------</td>
				<td>Schwimmanfänger</td>
				<td>---------</td>
				<td>---------</td>
				<td>Schwimmanfänger</td>
			</tr>
			<tr>
				<td id="time">15:00-16:30</td>
				<td>---------</td>
				<td>---------</td>
				<td>---------</td>
				<td>---------</td>
				<td>L1-L3</td>
			</tr>
			<tr>
				<td id="time">17:00-18:00</td>
				<td>Nachwuchsgruppen L2/L3</td>
				<td>---------</td>
				<td>L2/L3</td>
				<td>L1-L3 <p>in Battenberg</p></td>
				<td>---------</td>
			</tr>
			<tr>
				<td id="time">18:00-19:00</td>
				<td>L1-L3 + Schwimmanfänger</td>
				<td>---------</td>
				<td>L1-L3</td>
				<td>L1-L3 <p>in Battenberg</p></td>
				<td>---------</td>
			</tr>
			<tr>
				<td id="time">19:00-20:00</td>
				<td>L1</td>
				<td>---------</td>
				<td>L1-L3</td>
				<td>---------</td>
				<td>---------</td>
	        </tr>
				<td id="time">20:00-21:00</td>
				<td>Erwachsene/Triathlon</td>
				<td>---------</td>
				<td>Erwachsene/Triathlon</td>
				<td>---------</td>
				<td>---------</td>
			</tr>
		</table>
		<p id="p1">Die Uhrzeiten sind reine Trainingszeiten. Bitte immer 10 Minuten vorher da sein!<p>
		<p id="pEnde">Zusätzlich findet an wettkampffreien Samstagen Training von 12:30 - 14:30 Uhr in Battenberg statt.</p>
	</div>

{% endblock %}